### ISSUE TITLE
A tool to backport the edited GR2 (.model) files for Diablo 2 Resurrected

### ISSUE THREAD

**Issue by ghost** [ItsShiZZa/DiabloVision#1]
Hello ItsShiZZa,

Not sure if I should post it here, but I will try my luck. Is it possible for you to add import/export support of Diablo 2 Resurrected GR2 (.model)? It would greatly promote modding of the game. The same issue has already been opened in the Norbyte's repository but without any progress for a long time.

https://github.com/Norbyte/lslib/issues/67

**Comment by ItsShiZZa** [comment]
I don't have any experience with such things but have you seen the site https://www.d2rmodding.com (I'm not affiliated with them)? They seem to have a fairly alive D2R modding project going on over there that is geared more towards such things as your question as well as a series of link to their informative YouTube videos about modding the game.
